import type { MockDB } from '../core/MockDB';

/**
 * Seed forum module data
 * Uses the 10 canonical users (user-1 through user-10)
 */
export async function seedForum(db: MockDB): Promise<void> {
  const now = new Date();

  // Create posts
  db.posts.createMany([
    {
      id: 'post-1',
      title: 'How to write better code with ChatGPT?',
      content: `I recently started using ChatGPT to help write code, but I find that sometimes its answers are not quite accurate. I'd like to ask everyone what tips can help ChatGPT produce better code?

Here's what I currently do:
1. Describe requirements in as much detail as possible
2. Provide example code
3. Ask it to explain each step

But there are still some issues. Hope everyone can share their experience!`,
      authorId: 'user-1',
      category: 'question',
      upvotes: 48,
      downvotes: 6,
      score: 42,
      viewCount: 328,
      commentCount: 8,
      isPinned: false,
      isLocked: false,
      createdAt: new Date('2026-01-20T10:30:00'),
      updatedAt: new Date('2026-01-20T10:30:00'),
    },
    {
      id: 'post-2',
      title: '[Share] My Side Project completed in one week using AI',
      content: `I want to share a Side Project I recently completed using AI tools!

It's an automated content management system, mainly using:
- ChatGPT 4 for content generation
- Midjourney for image generation
- Make.com for workflow automation

The entire development process took about a week. Without AI, it might have taken more than a month.

Feel free to check it out, and suggestions are welcome!`,
      authorId: 'user-2',
      category: 'share',
      upvotes: 92,
      downvotes: 6,
      score: 86,
      viewCount: 512,
      commentCount: 12,
      isPinned: true,
      isLocked: false,
      createdAt: new Date('2026-01-19T15:00:00'),
      updatedAt: new Date('2026-01-19T18:30:00'),
    },
    {
      id: 'post-3',
      title: 'Midjourney v6 New Features Discussion',
      content: `Midjourney v6 is out! Has everyone tried it?

I noticed several obvious improvements:
1. Text generation is more accurate
2. Character fingers are no longer that weird
3. Lighting and shadows are more natural

However, there are also some issues, such as the generation speed seems a bit slower.

Does anyone have any insights to share?`,
      authorId: 'user-3',
      category: 'discussion',
      upvotes: 38,
      downvotes: 4,
      score: 34,
      viewCount: 245,
      commentCount: 10,
      isPinned: false,
      isLocked: false,
      createdAt: new Date('2026-01-18T09:15:00'),
      updatedAt: new Date('2026-01-18T09:15:00'),
    },
    {
      id: 'post-4',
      title: '[Resource] AI Tools Collection 2026 Edition',
      content: `I've compiled the latest list of AI tools for 2026. Hope it helps everyone!

## Text Generation
- ChatGPT 4 Turbo
- Claude 3
- Gemini Pro

## Image Generation
- Midjourney v6
- DALL-E 3
- Stable Diffusion XL

## Video Generation
- Runway Gen-2
- Pika Labs
- Sora (limited testing)

## Automation Tools
- Make.com
- Zapier
- n8n

Continuously updating. Feel free to add more!`,
      authorId: 'user-4',
      category: 'resource',
      upvotes: 162,
      downvotes: 6,
      score: 156,
      viewCount: 1024,
      commentCount: 15,
      isPinned: true,
      isLocked: false,
      createdAt: new Date('2026-01-15T14:00:00'),
      updatedAt: new Date('2026-01-20T11:00:00'),
    },
    {
      id: 'post-5',
      title: 'Beginner Question: How to start learning Prompt Engineering?',
      content: `Hello everyone, I'm new to AI and want to start learning Prompt Engineering.

I see related content in the courses, but I'd like to know first:
1. Do I need any prerequisite knowledge?
2. How long does it take to get started?
3. Is there a recommended learning sequence?

Thanks everyone!`,
      authorId: 'user-5',
      category: 'question',
      upvotes: 22,
      downvotes: 4,
      score: 18,
      viewCount: 156,
      commentCount: 7,
      isPinned: false,
      isLocked: false,
      createdAt: new Date('2026-01-21T08:00:00'),
      updatedAt: new Date('2026-01-21T08:00:00'),
    },
  ]);

  // Create post tags
  db.postTags.createMany([
    { id: 'ptag-1-1', postId: 'post-1', tag: 'ChatGPT' },
    { id: 'ptag-1-2', postId: 'post-1', tag: 'Programming' },
    { id: 'ptag-1-3', postId: 'post-1', tag: 'Tips' },
    { id: 'ptag-2-1', postId: 'post-2', tag: 'Side Project' },
    { id: 'ptag-2-2', postId: 'post-2', tag: 'AI Tools' },
    { id: 'ptag-2-3', postId: 'post-2', tag: 'Automation' },
    { id: 'ptag-3-1', postId: 'post-3', tag: 'Midjourney' },
    { id: 'ptag-3-2', postId: 'post-3', tag: 'Image Generation' },
    { id: 'ptag-3-3', postId: 'post-3', tag: 'New Features' },
    { id: 'ptag-4-1', postId: 'post-4', tag: 'AI Tools' },
    { id: 'ptag-4-2', postId: 'post-4', tag: 'Resources' },
    { id: 'ptag-4-3', postId: 'post-4', tag: '2026' },
    { id: 'ptag-5-1', postId: 'post-5', tag: 'Beginner' },
    { id: 'ptag-5-2', postId: 'post-5', tag: 'Prompt Engineering' },
    { id: 'ptag-5-3', postId: 'post-5', tag: 'Learning' },
  ]);

  // Create comments - matching the commentCount for each post
  db.comments.createMany([
    // ==========================================
    // Post 1 Comments (8 total)
    // ==========================================
    {
      id: 'comment-1-1',
      postId: 'post-1',
      authorId: 'user-2',
      content: 'My experience is to give ChatGPT more context, such as explaining your tech stack and project structure. This way it can give more relevant suggestions.',
      upvotes: 18,
      downvotes: 3,
      score: 15,
      isDeleted: false,
      createdAt: new Date('2026-01-20T11:00:00'),
      updatedAt: new Date('2026-01-20T11:00:00'),
    },
    {
      id: 'comment-1-2',
      postId: 'post-1',
      authorId: 'user-3',
      content: 'I recommend using the Chain of Thought approach, letting it think step by step. The accuracy will improve significantly!',
      upvotes: 14,
      downvotes: 2,
      score: 12,
      isDeleted: false,
      createdAt: new Date('2026-01-20T12:30:00'),
      updatedAt: new Date('2026-01-20T12:30:00'),
    },
    {
      id: 'comment-1-3',
      postId: 'post-1',
      parentId: 'comment-1-1',
      authorId: 'user-1',
      content: 'Thanks for sharing! I will try this method.',
      upvotes: 5,
      downvotes: 0,
      score: 5,
      isDeleted: false,
      createdAt: new Date('2026-01-20T13:00:00'),
      updatedAt: new Date('2026-01-20T13:00:00'),
    },
    {
      id: 'comment-1-4',
      postId: 'post-1',
      authorId: 'user-4',
      content: 'Also try specifying the output format you want - like asking for comments in the code, or specific variable naming conventions.',
      upvotes: 10,
      downvotes: 1,
      score: 9,
      isDeleted: false,
      createdAt: new Date('2026-01-20T14:15:00'),
      updatedAt: new Date('2026-01-20T14:15:00'),
    },
    {
      id: 'comment-1-5',
      postId: 'post-1',
      authorId: 'user-6',
      content: 'I find that asking ChatGPT to review its own code helps catch bugs before you even run it!',
      upvotes: 8,
      downvotes: 0,
      score: 8,
      isDeleted: false,
      createdAt: new Date('2026-01-20T15:30:00'),
      updatedAt: new Date('2026-01-20T15:30:00'),
    },
    {
      id: 'comment-1-6',
      postId: 'post-1',
      authorId: 'user-8',
      content: 'Breaking down complex problems into smaller tasks and tackling them one at a time really helps with accuracy.',
      upvotes: 6,
      downvotes: 1,
      score: 5,
      isDeleted: false,
      createdAt: new Date('2026-01-20T16:00:00'),
      updatedAt: new Date('2026-01-20T16:00:00'),
    },
    {
      id: 'comment-1-7',
      postId: 'post-1',
      authorId: 'user-9',
      content: 'Have you tried using the new GPT-4 Turbo? The code quality has improved noticeably compared to the older versions.',
      upvotes: 7,
      downvotes: 0,
      score: 7,
      isDeleted: false,
      createdAt: new Date('2026-01-20T17:20:00'),
      updatedAt: new Date('2026-01-20T17:20:00'),
    },
    {
      id: 'comment-1-8',
      postId: 'post-1',
      authorId: 'user-10',
      content: 'Pro tip: Always include error handling requirements in your prompts. ChatGPT often skips edge cases unless you explicitly ask.',
      upvotes: 12,
      downvotes: 1,
      score: 11,
      isDeleted: false,
      createdAt: new Date('2026-01-20T18:00:00'),
      updatedAt: new Date('2026-01-20T18:00:00'),
    },

    // ==========================================
    // Post 2 Comments (12 total)
    // ==========================================
    {
      id: 'comment-2-1',
      postId: 'post-2',
      authorId: 'user-1',
      content: 'Amazing! Is Make.com hard to learn? I\'ve been wanting to try automation tools.',
      upvotes: 8,
      downvotes: 0,
      score: 8,
      isDeleted: false,
      createdAt: new Date('2026-01-19T16:00:00'),
      updatedAt: new Date('2026-01-19T16:00:00'),
    },
    {
      id: 'comment-2-2',
      postId: 'post-2',
      parentId: 'comment-2-1',
      authorId: 'user-2',
      content: 'Not at all! Make.com has a visual interface that makes it super intuitive. I went from zero to building workflows in just a few hours.',
      upvotes: 10,
      downvotes: 0,
      score: 10,
      isDeleted: false,
      createdAt: new Date('2026-01-19T16:30:00'),
      updatedAt: new Date('2026-01-19T16:30:00'),
    },
    {
      id: 'comment-2-3',
      postId: 'post-2',
      authorId: 'user-3',
      content: 'This is inspiring! What was the most challenging part of the project?',
      upvotes: 6,
      downvotes: 0,
      score: 6,
      isDeleted: false,
      createdAt: new Date('2026-01-19T17:00:00'),
      updatedAt: new Date('2026-01-19T17:00:00'),
    },
    {
      id: 'comment-2-4',
      postId: 'post-2',
      parentId: 'comment-2-3',
      authorId: 'user-2',
      content: 'Honestly, the hardest part was getting the Midjourney prompts just right for consistent brand visuals. Took some trial and error.',
      upvotes: 9,
      downvotes: 1,
      score: 8,
      isDeleted: false,
      createdAt: new Date('2026-01-19T17:30:00'),
      updatedAt: new Date('2026-01-19T17:30:00'),
    },
    {
      id: 'comment-2-5',
      postId: 'post-2',
      authorId: 'user-4',
      content: 'Love this! I\'m working on something similar. Do you have any tips for integrating ChatGPT API with Make.com?',
      upvotes: 7,
      downvotes: 0,
      score: 7,
      isDeleted: false,
      createdAt: new Date('2026-01-19T18:00:00'),
      updatedAt: new Date('2026-01-19T18:00:00'),
    },
    {
      id: 'comment-2-6',
      postId: 'post-2',
      authorId: 'user-5',
      content: 'As a beginner, this really shows what\'s possible with AI tools. Bookmarked for future reference!',
      upvotes: 4,
      downvotes: 0,
      score: 4,
      isDeleted: false,
      createdAt: new Date('2026-01-19T19:00:00'),
      updatedAt: new Date('2026-01-19T19:00:00'),
    },
    {
      id: 'comment-2-7',
      postId: 'post-2',
      authorId: 'user-6',
      content: 'How much does it cost to run this system monthly? Curious about the API costs.',
      upvotes: 11,
      downvotes: 0,
      score: 11,
      isDeleted: false,
      createdAt: new Date('2026-01-19T19:30:00'),
      updatedAt: new Date('2026-01-19T19:30:00'),
    },
    {
      id: 'comment-2-8',
      postId: 'post-2',
      parentId: 'comment-2-7',
      authorId: 'user-2',
      content: 'Great question! It\'s about $50-80/month depending on usage. ChatGPT API is the biggest cost, Midjourney is a flat subscription.',
      upvotes: 15,
      downvotes: 0,
      score: 15,
      isDeleted: false,
      createdAt: new Date('2026-01-19T20:00:00'),
      updatedAt: new Date('2026-01-19T20:00:00'),
    },
    {
      id: 'comment-2-9',
      postId: 'post-2',
      authorId: 'user-7',
      content: 'Would you consider open-sourcing the Make.com templates? Would love to learn from your setup.',
      upvotes: 8,
      downvotes: 0,
      score: 8,
      isDeleted: false,
      createdAt: new Date('2026-01-19T21:00:00'),
      updatedAt: new Date('2026-01-19T21:00:00'),
    },
    {
      id: 'comment-2-10',
      postId: 'post-2',
      authorId: 'user-8',
      content: 'This is exactly what I needed to see! Been procrastinating on my own project. Time to start!',
      upvotes: 5,
      downvotes: 0,
      score: 5,
      isDeleted: false,
      createdAt: new Date('2026-01-19T22:00:00'),
      updatedAt: new Date('2026-01-19T22:00:00'),
    },
    {
      id: 'comment-2-11',
      postId: 'post-2',
      authorId: 'user-9',
      content: 'The combination of tools you picked is solid. Have you considered adding n8n for more complex logic?',
      upvotes: 6,
      downvotes: 0,
      score: 6,
      isDeleted: false,
      createdAt: new Date('2026-01-19T23:00:00'),
      updatedAt: new Date('2026-01-19T23:00:00'),
    },
    {
      id: 'comment-2-12',
      postId: 'post-2',
      authorId: 'user-10',
      content: 'Excellent execution! This kind of project showcase is why I love this community. Keep sharing!',
      upvotes: 9,
      downvotes: 0,
      score: 9,
      isDeleted: false,
      createdAt: new Date('2026-01-20T08:00:00'),
      updatedAt: new Date('2026-01-20T08:00:00'),
    },

    // ==========================================
    // Post 3 Comments (10 total)
    // ==========================================
    {
      id: 'comment-3-1',
      postId: 'post-3',
      authorId: 'user-1',
      content: 'Yes! The text generation improvement is huge. Finally can add proper text to images without weird characters.',
      upvotes: 12,
      downvotes: 1,
      score: 11,
      isDeleted: false,
      createdAt: new Date('2026-01-18T10:00:00'),
      updatedAt: new Date('2026-01-18T10:00:00'),
    },
    {
      id: 'comment-3-2',
      postId: 'post-3',
      authorId: 'user-2',
      content: 'The finger issue fix is such a relief! My character designs look so much more natural now.',
      upvotes: 15,
      downvotes: 0,
      score: 15,
      isDeleted: false,
      createdAt: new Date('2026-01-18T10:30:00'),
      updatedAt: new Date('2026-01-18T10:30:00'),
    },
    {
      id: 'comment-3-3',
      postId: 'post-3',
      authorId: 'user-4',
      content: 'I noticed the --style raw parameter gives even better results in v6. Has anyone experimented with it?',
      upvotes: 9,
      downvotes: 0,
      score: 9,
      isDeleted: false,
      createdAt: new Date('2026-01-18T11:00:00'),
      updatedAt: new Date('2026-01-18T11:00:00'),
    },
    {
      id: 'comment-3-4',
      postId: 'post-3',
      parentId: 'comment-3-3',
      authorId: 'user-6',
      content: 'Yes! --style raw is amazing for photorealistic images. Less "AI look" if that makes sense.',
      upvotes: 8,
      downvotes: 0,
      score: 8,
      isDeleted: false,
      createdAt: new Date('2026-01-18T11:30:00'),
      updatedAt: new Date('2026-01-18T11:30:00'),
    },
    {
      id: 'comment-3-5',
      postId: 'post-3',
      authorId: 'user-5',
      content: 'As someone just starting with image generation, should I begin with v6 or learn the basics with v5 first?',
      upvotes: 5,
      downvotes: 0,
      score: 5,
      isDeleted: false,
      createdAt: new Date('2026-01-18T12:00:00'),
      updatedAt: new Date('2026-01-18T12:00:00'),
    },
    {
      id: 'comment-3-6',
      postId: 'post-3',
      parentId: 'comment-3-5',
      authorId: 'user-3',
      content: 'Definitely start with v6! It\'s more intuitive and the prompts work more naturally. No reason to learn older versions.',
      upvotes: 7,
      downvotes: 0,
      score: 7,
      isDeleted: false,
      createdAt: new Date('2026-01-18T12:30:00'),
      updatedAt: new Date('2026-01-18T12:30:00'),
    },
    {
      id: 'comment-3-7',
      postId: 'post-3',
      authorId: 'user-7',
      content: 'The slower speed is noticeable but honestly worth it for the quality improvement.',
      upvotes: 6,
      downvotes: 1,
      score: 5,
      isDeleted: false,
      createdAt: new Date('2026-01-18T13:00:00'),
      updatedAt: new Date('2026-01-18T13:00:00'),
    },
    {
      id: 'comment-3-8',
      postId: 'post-3',
      authorId: 'user-8',
      content: 'Anyone else notice the prompt understanding is way better? Less need for negative prompts now.',
      upvotes: 10,
      downvotes: 0,
      score: 10,
      isDeleted: false,
      createdAt: new Date('2026-01-18T14:00:00'),
      updatedAt: new Date('2026-01-18T14:00:00'),
    },
    {
      id: 'comment-3-9',
      postId: 'post-3',
      authorId: 'user-9',
      content: 'The aspect ratio options are also better. Getting cinematic 21:9 shots is so much easier now.',
      upvotes: 8,
      downvotes: 0,
      score: 8,
      isDeleted: false,
      createdAt: new Date('2026-01-18T15:00:00'),
      updatedAt: new Date('2026-01-18T15:00:00'),
    },
    {
      id: 'comment-3-10',
      postId: 'post-3',
      authorId: 'user-10',
      content: 'Great discussion! I\'m compiling a v6 tips document. Will share it once it\'s ready.',
      upvotes: 14,
      downvotes: 0,
      score: 14,
      isDeleted: false,
      createdAt: new Date('2026-01-18T16:00:00'),
      updatedAt: new Date('2026-01-18T16:00:00'),
    },

    // ==========================================
    // Post 4 Comments (15 total)
    // ==========================================
    {
      id: 'comment-4-1',
      postId: 'post-4',
      authorId: 'user-1',
      content: 'This list is incredibly comprehensive! Adding to my bookmarks.',
      upvotes: 12,
      downvotes: 0,
      score: 12,
      isDeleted: false,
      createdAt: new Date('2026-01-15T15:00:00'),
      updatedAt: new Date('2026-01-15T15:00:00'),
    },
    {
      id: 'comment-4-2',
      postId: 'post-4',
      authorId: 'user-2',
      content: 'You might want to add Perplexity AI to the text generation section - it\'s great for research.',
      upvotes: 18,
      downvotes: 1,
      score: 17,
      isDeleted: false,
      createdAt: new Date('2026-01-15T16:00:00'),
      updatedAt: new Date('2026-01-15T16:00:00'),
    },
    {
      id: 'comment-4-3',
      postId: 'post-4',
      parentId: 'comment-4-2',
      authorId: 'user-4',
      content: 'Good suggestion! I\'ll add Perplexity and a few other research-focused tools.',
      upvotes: 8,
      downvotes: 0,
      score: 8,
      isDeleted: false,
      createdAt: new Date('2026-01-15T16:30:00'),
      updatedAt: new Date('2026-01-15T16:30:00'),
    },
    {
      id: 'comment-4-4',
      postId: 'post-4',
      authorId: 'user-3',
      content: 'For video generation, Kling AI is also worth mentioning. Great for longer videos.',
      upvotes: 9,
      downvotes: 0,
      score: 9,
      isDeleted: false,
      createdAt: new Date('2026-01-15T17:00:00'),
      updatedAt: new Date('2026-01-15T17:00:00'),
    },
    {
      id: 'comment-4-5',
      postId: 'post-4',
      authorId: 'user-5',
      content: 'Perfect timing! I was just looking for a guide like this. Thank you so much!',
      upvotes: 5,
      downvotes: 0,
      score: 5,
      isDeleted: false,
      createdAt: new Date('2026-01-15T18:00:00'),
      updatedAt: new Date('2026-01-15T18:00:00'),
    },
    {
      id: 'comment-4-6',
      postId: 'post-4',
      authorId: 'user-6',
      content: 'Would be great to add a section for AI coding assistants - Cursor, GitHub Copilot, etc.',
      upvotes: 14,
      downvotes: 0,
      score: 14,
      isDeleted: false,
      createdAt: new Date('2026-01-16T09:00:00'),
      updatedAt: new Date('2026-01-16T09:00:00'),
    },
    {
      id: 'comment-4-7',
      postId: 'post-4',
      authorId: 'user-7',
      content: 'Has anyone tried Leonardo AI for image generation? How does it compare to Midjourney?',
      upvotes: 7,
      downvotes: 0,
      score: 7,
      isDeleted: false,
      createdAt: new Date('2026-01-16T10:00:00'),
      updatedAt: new Date('2026-01-16T10:00:00'),
    },
    {
      id: 'comment-4-8',
      postId: 'post-4',
      parentId: 'comment-4-7',
      authorId: 'user-8',
      content: 'Leonardo is great for gaming art and has better fine-tuning options. Midjourney is still king for general use.',
      upvotes: 11,
      downvotes: 0,
      score: 11,
      isDeleted: false,
      createdAt: new Date('2026-01-16T11:00:00'),
      updatedAt: new Date('2026-01-16T11:00:00'),
    },
    {
      id: 'comment-4-9',
      postId: 'post-4',
      authorId: 'user-9',
      content: 'Don\'t forget ElevenLabs for voice generation! Essential for video content.',
      upvotes: 13,
      downvotes: 0,
      score: 13,
      isDeleted: false,
      createdAt: new Date('2026-01-17T08:00:00'),
      updatedAt: new Date('2026-01-17T08:00:00'),
    },
    {
      id: 'comment-4-10',
      postId: 'post-4',
      authorId: 'user-10',
      content: 'This should be pinned! Maybe add difficulty levels for beginners to know where to start.',
      upvotes: 16,
      downvotes: 0,
      score: 16,
      isDeleted: false,
      createdAt: new Date('2026-01-17T10:00:00'),
      updatedAt: new Date('2026-01-17T10:00:00'),
    },
    {
      id: 'comment-4-11',
      postId: 'post-4',
      authorId: 'user-1',
      content: 'For automation, Bardeen is also worth checking out. Great for browser-based tasks.',
      upvotes: 6,
      downvotes: 0,
      score: 6,
      isDeleted: false,
      createdAt: new Date('2026-01-18T09:00:00'),
      updatedAt: new Date('2026-01-18T09:00:00'),
    },
    {
      id: 'comment-4-12',
      postId: 'post-4',
      authorId: 'user-2',
      content: 'Would love to see a comparison section too - pros and cons of each tool.',
      upvotes: 10,
      downvotes: 0,
      score: 10,
      isDeleted: false,
      createdAt: new Date('2026-01-19T11:00:00'),
      updatedAt: new Date('2026-01-19T11:00:00'),
    },
    {
      id: 'comment-4-13',
      postId: 'post-4',
      authorId: 'user-3',
      content: 'Notion AI is great for writing assistance if you\'re already in the Notion ecosystem.',
      upvotes: 7,
      downvotes: 0,
      score: 7,
      isDeleted: false,
      createdAt: new Date('2026-01-19T14:00:00'),
      updatedAt: new Date('2026-01-19T14:00:00'),
    },
    {
      id: 'comment-4-14',
      postId: 'post-4',
      authorId: 'user-6',
      content: 'Updated my workflow based on this list. Productivity has gone through the roof!',
      upvotes: 8,
      downvotes: 0,
      score: 8,
      isDeleted: false,
      createdAt: new Date('2026-01-20T08:00:00'),
      updatedAt: new Date('2026-01-20T08:00:00'),
    },
    {
      id: 'comment-4-15',
      postId: 'post-4',
      authorId: 'user-8',
      content: 'Thanks for keeping this updated! This is my go-to resource for trying new tools.',
      upvotes: 9,
      downvotes: 0,
      score: 9,
      isDeleted: false,
      createdAt: new Date('2026-01-20T15:00:00'),
      updatedAt: new Date('2026-01-20T15:00:00'),
    },

    // ==========================================
    // Post 5 Comments (7 total)
    // ==========================================
    {
      id: 'comment-5-1',
      postId: 'post-5',
      authorId: 'user-2',
      content: 'You don\'t need much prerequisite knowledge. I recommend starting with the free courses here and following along - you\'ll get the hang of it!',
      upvotes: 10,
      downvotes: 1,
      score: 9,
      isDeleted: false,
      createdAt: new Date('2026-01-21T09:00:00'),
      updatedAt: new Date('2026-01-21T09:00:00'),
    },
    {
      id: 'comment-5-2',
      postId: 'post-5',
      authorId: 'user-4',
      content: 'The basics can be learned in a weekend, but mastery takes continuous practice. Start simple and build up!',
      upvotes: 8,
      downvotes: 0,
      score: 8,
      isDeleted: false,
      createdAt: new Date('2026-01-21T10:00:00'),
      updatedAt: new Date('2026-01-21T10:00:00'),
    },
    {
      id: 'comment-5-3',
      postId: 'post-5',
      authorId: 'user-10',
      content: 'Welcome! I suggest: 1) Basic prompting course, 2) Practice daily with ChatGPT, 3) Move to specialized tools. Took me about 2 weeks to feel comfortable.',
      upvotes: 15,
      downvotes: 0,
      score: 15,
      isDeleted: false,
      createdAt: new Date('2026-01-21T11:00:00'),
      updatedAt: new Date('2026-01-21T11:00:00'),
    },
    {
      id: 'comment-5-4',
      postId: 'post-5',
      parentId: 'comment-5-3',
      authorId: 'user-5',
      content: 'This is exactly what I needed! Thank you for the clear roadmap!',
      upvotes: 4,
      downvotes: 0,
      score: 4,
      isDeleted: false,
      createdAt: new Date('2026-01-21T11:30:00'),
      updatedAt: new Date('2026-01-21T11:30:00'),
    },
    {
      id: 'comment-5-5',
      postId: 'post-5',
      authorId: 'user-3',
      content: 'No programming background needed! I started with zero tech experience and now I use AI daily for work.',
      upvotes: 7,
      downvotes: 0,
      score: 7,
      isDeleted: false,
      createdAt: new Date('2026-01-21T12:00:00'),
      updatedAt: new Date('2026-01-21T12:00:00'),
    },
    {
      id: 'comment-5-6',
      postId: 'post-5',
      authorId: 'user-6',
      content: 'Join the community Discord too! We have weekly prompt challenges that really help with learning.',
      upvotes: 6,
      downvotes: 0,
      score: 6,
      isDeleted: false,
      createdAt: new Date('2026-01-21T13:00:00'),
      updatedAt: new Date('2026-01-21T13:00:00'),
    },
    {
      id: 'comment-5-7',
      postId: 'post-5',
      authorId: 'user-9',
      content: 'The most important thing is just to start experimenting. Don\'t worry about being perfect - that\'s how we all learned!',
      upvotes: 9,
      downvotes: 0,
      score: 9,
      isDeleted: false,
      createdAt: new Date('2026-01-21T14:00:00'),
      updatedAt: new Date('2026-01-21T14:00:00'),
    },
  ]);

  // Create some votes
  db.votes.createMany([
    { id: 'vote-1', userId: 'user-2', targetType: 'post', targetId: 'post-1', voteType: 'upvote', createdAt: now },
    { id: 'vote-2', userId: 'user-3', targetType: 'post', targetId: 'post-1', voteType: 'upvote', createdAt: now },
    { id: 'vote-3', userId: 'user-4', targetType: 'post', targetId: 'post-2', voteType: 'upvote', createdAt: now },
    { id: 'vote-4', userId: 'user-5', targetType: 'post', targetId: 'post-2', voteType: 'upvote', createdAt: now },
    { id: 'vote-5', userId: 'user-6', targetType: 'post', targetId: 'post-3', voteType: 'upvote', createdAt: now },
    { id: 'vote-6', userId: 'user-7', targetType: 'post', targetId: 'post-3', voteType: 'upvote', createdAt: now },
    { id: 'vote-7', userId: 'user-8', targetType: 'post', targetId: 'post-4', voteType: 'upvote', createdAt: now },
    { id: 'vote-8', userId: 'user-9', targetType: 'post', targetId: 'post-4', voteType: 'upvote', createdAt: now },
    { id: 'vote-9', userId: 'user-10', targetType: 'post', targetId: 'post-5', voteType: 'upvote', createdAt: now },
    { id: 'vote-10', userId: 'user-1', targetType: 'comment', targetId: 'comment-1-1', voteType: 'upvote', createdAt: now },
    { id: 'vote-11', userId: 'user-1', targetType: 'comment', targetId: 'comment-1-2', voteType: 'upvote', createdAt: now },
    { id: 'vote-12', userId: 'user-3', targetType: 'comment', targetId: 'comment-2-1', voteType: 'upvote', createdAt: now },
  ]);
}
